name: CI with Shared Output

on:
  push:
    branches: [ master ]

jobs:
  list-dir:
    runs-on: ubuntu-latest
    outputs:
      dir_content: ${{ steps.save_output.outputs.dir_content }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: List files and export to output
        id: save_output
        run: |
          DIR_OUTPUT="$(ls -la)"
          echo "dir_content<<EOF" >> $GITHUB_OUTPUT
          echo "$DIR_OUTPUT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

  echo-dir:
    needs: list-dir
    runs-on: ubuntu-latest
    steps:
      - name: Echo directory output from previous job
        run: |
          echo "${{ needs.list-dir.outputs.dir_content }}"
