name: CI with Artifact Upload

on:
  push:
    branches: [ master ]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Create artifact file using Python
        run: |
          echo 'print("Hello from Artifact")' > script.py
          python3 script.py > output.txt
          echo "This is a test artifact." >> output.txt

      - name: List files
        run: ls -la

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: test-output
          path: output.txt
