name: Parallel CI Test

on: [push, workflow_dispatch]

jobs:
  run-script-1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run script1
        run: python3 script1.py

  run-script-2:
    # needs: run-script-1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run script2
        run: python3 script2.py
